from typing import Optional, Protocol


class ThreadRepository(Protocol):
    """Read/write threaded research history (swap Postgres via adapter)."""

    async def create_thread(self, title: str) -> Optional[str]: ...

    async def list_threads(self, limit: int = 30) -> list[dict]: ...

    async def get_thread(self, thread_id: str) -> Optional[dict]: ...

    async def delete_thread(self, thread_id: str) -> bool: ...

    async def get_prior_context(self, thread_id: str) -> Optional[str]: ...
